# -*- coding: utf-8 -*-
# ---------------------------------------------------------------------------
# code_alpha_num_auto_de_segments.py
# Created on: 2021-08-12 13:50:58.00000
#   (generated by ArcGIS/ModelBuilder)
# Usage: code_alpha_num_auto_de_segments <Inuput__Couche_vectorielle_de_type_ligne__> <Workspace_Geodatabase_> 
# Description: 
# ---------------------------------------------------------------------------

# Import arcpy module
import arcpy

# Load required toolboxes
arcpy.ImportToolbox("C:/GIS/Shoreline/code_Alphanumerique/Segmentation_Numérotation.tbx")

# Script arguments
Inuput__Couche_vectorielle_de_type_ligne__ = arcpy.GetParameterAsText(0)
if Inuput__Couche_vectorielle_de_type_ligne__ == '#' or not Inuput__Couche_vectorielle_de_type_ligne__:
    Inuput__Couche_vectorielle_de_type_ligne__ = "cob" # provide a default value if unspecified

Workspace_Geodatabase_ = arcpy.GetParameterAsText(1)
if Workspace_Geodatabase_ == '#' or not Workspace_Geodatabase_:
    Workspace_Geodatabase_ = "C:\\GIS\\ascup2.mdb" # provide a default value if unspecified

# Local variables:
Output__Couche_vectorielle_de_type_ligne_Lignes_ = "%Workspace[Geodatabase]%\\Lignes"
Lignes_1_ = Output__Couche_vectorielle_de_type_ligne_Lignes_
Lignes__3_ = Lignes_1_
Lignes__4_ = Lignes_1_
Lignes__6_ = Lignes_1_
Lignes__2_ = Lignes__3_
Lignes__5_ = Lignes__2_
Lignes_feature_layer__2_ = Lignes__6_
Lignes_feature_layer = Lignes__4_
Lignes = "Lignes"
Polylignes_en_sorties__Résultat_intermédiaire_ = "%Workspace[Geodatabase]%\\Polyligne"
Polylignes = "Polylignes"

# Process: Spatial Join
arcpy.SpatialJoin_analysis(Inuput__Couche_vectorielle_de_type_ligne__, Inuput__Couche_vectorielle_de_type_ligne__, Output__Couche_vectorielle_de_type_ligne_Lignes_, "JOIN_ONE_TO_ONE", "KEEP_COMMON", "", "INTERSECT", "", "")

# Process: Calculate Field
arcpy.CalculateField_management(Output__Couche_vectorielle_de_type_ligne_Lignes_, "Join_Count", "[Join_Count] -1", "VB", "")

# Process: Add Field
arcpy.AddField_management(Lignes_1_, "etat", "DOUBLE", "", "", "", "", "NULLABLE", "NON_REQUIRED", "")

# Process: Calculate Field (2)
arcpy.CalculateField_management(Lignes__3_, "etat", "[Join_Count]", "VB", "")

# Process: Delete Field
arcpy.DeleteField_management(Lignes__2_, "Join_Count")

# Process: Add Field (3)
arcpy.AddField_management(Lignes_1_, "sens", "DOUBLE", "", "", "", "", "NULLABLE", "NON_REQUIRED", "")

# Process: Calculate Field (4)
arcpy.CalculateField_management(Lignes__6_, "sens", "0", "VB", "")

# Process: Add Field (2)
arcpy.AddField_management(Lignes_1_, "num_test", "DOUBLE", "", "", "", "", "NULLABLE", "NON_REQUIRED", "")

# Process: Calculate Field (3)
arcpy.CalculateField_management(Lignes__4_, "num_test", "0", "VB", "")

# Process: Make Feature Layer (2)
arcpy.MakeFeatureLayer_management(Lignes_feature_layer, Lignes, "", "", "OBJECTID_1 OBJECTID_1 VISIBLE NONE;Shape Shape VISIBLE NONE;Join_Count Join_Count VISIBLE NONE;TARGET_FID TARGET_FID VISIBLE NONE;num_test num_test VISIBLE NONE")

# Process: Dissolve
arcpy.Dissolve_management(Inuput__Couche_vectorielle_de_type_ligne__, Polylignes_en_sorties__Résultat_intermédiaire_, "", "", "SINGLE_PART", "DISSOLVE_LINES")

# Process: Make Feature Layer
arcpy.MakeFeatureLayer_management(Polylignes_en_sorties__Résultat_intermédiaire_, Polylignes, "", "", "OBJECTID OBJECTID VISIBLE NONE;Shape Shape VISIBLE NONE")

# Process: Segment Ouvert
arcpy.gp.toolbox = "C:/GIS/Shoreline/code_Alphanumerique/Segmentation_Numérotation.tbx";
# Warning: the toolbox C:/GIS/Shoreline/code_Alphanumerique/Segmentation_Numérotation.tbx DOES NOT have an alias. 
# Please assign this toolbox an alias to avoid tool name collisions
# And replace arcpy.gp.Model7(...) with arcpy.Model7_ALIAS(...)
arcpy.gp.Model7(Lignes, Polylignes)

# Process: Segment Fermé
arcpy.gp.toolbox = "C:/GIS/Shoreline/code_Alphanumerique/Segmentation_Numérotation.tbx";
# Warning: the toolbox C:/GIS/Shoreline/code_Alphanumerique/Segmentation_Numérotation.tbx DOES NOT have an alias. 
# Please assign this toolbox an alias to avoid tool name collisions
# And replace arcpy.gp.Model10(...) with arcpy.Model10_ALIAS(...)
arcpy.gp.Model10(Lignes, Polylignes)

# Process: Segment Unique
arcpy.gp.toolbox = "C:/GIS/Shoreline/code_Alphanumerique/Segmentation_Numérotation.tbx";
# Warning: the toolbox C:/GIS/Shoreline/code_Alphanumerique/Segmentation_Numérotation.tbx DOES NOT have an alias. 
# Please assign this toolbox an alias to avoid tool name collisions
# And replace arcpy.gp.Model6(...) with arcpy.Model6_ALIAS(...)
arcpy.gp.Model6(Lignes, Lignes)

